CREATE TABLE BLOCKCHAIN.SC_ORDER ( ORDER_NO VARCHAR(45) , 
	BUYER_ID VARCHAR(256) , SELLER_ID VARCHAR(256),
	PRIMARY KEY (ORDER_NO,BUYER_ID,SELLER_ID)) ;
	
	
CREATE TABLE BLOCKCHAIN.SC_ORDER_LINE ( ORDER_NO VARCHAR(256), ORDER_LINE_NO VARCHAR(45) , 
	SHIP_FROM_ID VARCHAR(256) , SHIP_TO_ID VARCHAR(256) , QUANTITY DECIMAL(20,6), 
	ITEM_ID VARCHAR(45) , UOM VARCHAR(10) ,  
	PRIMARY KEY (ORDER_NO,ORDER_LINE_NO)) ;

